name: Build ESP32-C3 Firmware

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v5.0
    steps:
      - uses: actions/checkout@v4

      - name: Build for ESP32-C3
        shell: bash
        run: |
          idf.py set-target esp32c3
          idf.py build

      - name: Rename output binary
        shell: bash
        run: cp build/esp32_mouse_keyboard.bin build/esp32c3_hid_mouse_keyboard.bin

      - name: Upload firmware binaries
        uses: actions/upload-artifact@v4
        with:
          name: esp32c3_hid_mouse_keyboard
          path: |
            build/esp32c3_hid_mouse_keyboard.bin
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
